services:

  # PostgreSQL database service
  postgres:
    image: postgres:16
    env_file: 
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Main API service
  api:
    restart: on-failure
    build:
      context: projects/api
      dockerfile: compose/local/Dockerfile
    env_file:
      - .env
    volumes:
      - ./projects/api:/app
      - api-tmp:/tmp
    command: /start
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
  
  # Redis service for message brokering with Celery
  redis:
    image: redis:7

  # Celery worker for asynchronous task processing
  celery_worker:
    build:
      context: projects/api
      dockerfile: compose/local/Dockerfile
    command: /celery-worker-start
    volumes:
      - ./projects/api:/app
      - api-tmp:/tmp
    env_file:
      - .env
    depends_on:
      - redis
      - postgres

  # Scheduler for periodic Celery tasks
  celery_beat:
    build:
      context: projects/api
      dockerfile: compose/local/Dockerfile
    image: api_celery_beat
    command: /celery-beat-start
    volumes:
      - ./projects/api:/app
    env_file:
      - .env
    depends_on:
      - redis
      - postgres

  # Interface to monitor Celery tasks
  flower:
    build:
      context: projects/api
      dockerfile: compose/local/Dockerfile
    image: api_celery_flower
    command: /celery-worker-start
    volumes:
      - ./projects/api:/app
    env_file:
      - .env
    ports:
      - 5555:5555
    depends_on:
      - redis
      - postgres

  app:
    restart: on-failure
    build:
      context: projects/app
      dockerfile: Dockerfile
    volumes:
      - ./projects/app:/code
      - app-node-modules:/code/node_modules
    command: "npm run start"
    ports:
      - "4200:4200"

  # Internal Documentation based on MkDocs
  documentation:
    build:
      context: projects/docs
    volumes:
      - ./projects/docs:/code
      - documentation-node-modules:/code/node_modules
    command: "mkdocs serve"
    ports:
      - "8001:8001"

volumes:
  app-node-modules:
    external: false
  documentation-node-modules:
    external: false
  api-tmp:
    external: false
  postgres_data:
    external: false
